`include "riscv_isa_defines.v"

`define ISR_BASE_ADDR 32'h1C00_0000

`define ALU_ADD  7'b??0000?
`define ALU_SUB  7'b1000001
`define ALU_AND  7'b??1110?
`define ALU_OR   7'b??1100?
`define ALU_XOR  7'b??1000?
`define ALU_SLL  7'b000010?
`define ALU_SRA  7'b101010?
`define ALU_SRL  7'b001010?
`define ALU_SLT  7'b??0100?
`define ALU_SLTU 7'b??0110?
`define ALU_EQ   7'b??00011
`define ALU_NE   7'b??00111
`define ALU_LT   7'b??10011
`define ALU_GE   7'b??10111
`define ALU_LTU  7'b??11011
`define ALU_GEU  7'b??11111
`define ALU_MUL  7'b0100001

`define IMM_ZERO 3'd0
`define IMM_I 3'd1
`define IMM_S 3'd2
`define IMM_B 3'd3
`define IMM_U 3'd4
`define IMM_J 3'd5
`define IMM_CONST_4 3'd6

`define CTRL_STATE_BITS 5
`define CTRL_STATE_INIT `CTRL_STATE_BITS'd0
`define CTRL_STATE_REQ `CTRL_STATE_BITS'd1
`define CTRL_STATE_LOAD `CTRL_STATE_BITS'd2
`define CTRL_STATE_OP `CTRL_STATE_BITS'd3
`define CTRL_STATE_OPIMM `CTRL_STATE_BITS'd4
`define CTRL_STATE_BR_CMP `CTRL_STATE_BITS'd5
`define CTRL_STATE_BR_JUMP `CTRL_STATE_BITS'd6
`define CTRL_STATE_CONT `CTRL_STATE_BITS'd7
`define CTRL_STATE_JALX_LINK `CTRL_STATE_BITS'd8
`define CTRL_STATE_JAL_JUMP `CTRL_STATE_BITS'd9
`define CTRL_STATE_JALR_JUMP `CTRL_STATE_BITS'd10
`define CTRL_STATE_AUIPC `CTRL_STATE_BITS'd11
`define CTRL_STATE_LUI `CTRL_STATE_BITS'd12
`define CTRL_STATE_LW_REQ `CTRL_STATE_BITS'd13
`define CTRL_STATE_LW_LOAD `CTRL_STATE_BITS'd14
`define CTRL_STATE_SW `CTRL_STATE_BITS'd15
`define CTRL_STATE_MRET `CTRL_STATE_BITS'd16
`define CTRL_STATE_ENTER_ISR `CTRL_STATE_BITS'd17
`define CTRL_STATE_MUL_BEGIN `CTRL_STATE_BITS'd18
`define CTRL_STATE_MUL_WRITEBACK `CTRL_STATE_BITS'd19
`define CTRL_STATE_CSRR `CTRL_STATE_BITS'd20

`define CACHE_STATE_WAIT 2'd0
`define CACHE_STATE_REQUEST 2'd1
`define CACHE_STATE_FULFILL 2'd2

`define MEM_STATE_WAIT 3'd0
`define MEM_STATE_REQ_A 3'd1
`define MEM_STATE_REQ_B 3'd2
`define MEM_STATE_FULFILL 3'd3