`define OPCODE_OP       7'h33
`define OPCODE_OPIMM    7'h13
`define OPCODE_STORE    7'h23
`define OPCODE_LOAD     7'h03
`define OPCODE_BRANCH   7'h63
`define OPCODE_JALR     7'h67
`define OPCODE_JAL      7'h6f
`define OPCODE_AUIPC    7'h17
`define OPCODE_LUI      7'h37
`define OPCODE_SYS      7'h73